baseurl = ""
title = "Akhil Tulluri"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

[params]
  author = "Akhil Tulluri"
  info = "Technical Lead"
  description = "Akhil's landing page"
  keywords = "landing,personal.developer"
  avatarurl = "images/avatar.jpg"
  favicon_32 = "images/favicon-32x32.png"
  favicon_16 = "images/favicon-16x16.png"
  colorScheme = "auto"
  hidecolorschemetoggle = false

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/officialakhil/"